name: tst

on:
  workflow_dispatch:

env:
  REPO_URL: https://api.github.com/repos/Kava-Labs/kava/releases/latest
  VERSION_STR: KAVA_VERSION
  SUFFIX_STR: KAVA_SUFFIX
  WORKING_DIR: containers/kava

jobs:
  build_and_upload:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Get versions
      id: get_versions
      run: |
          echo ::set-output name=release_tag::$(curl -sL $REPO_URL | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(export $(grep -e ${VERSION_STR} -e ${SUFFIX_STR} .env | xargs) && echo "v${!VERSION_STR}${!SUFFIX_STR}")
          echo "release_tag=${steps.get_versions.outputs.release_tag}"
          echo "current_tag=${steps.get_versions.outputs.current_tag}"
      working-directory: ${{ WORKING_DIR }}

    - name: Build
      if: steps.get_versions.outputs.release_tag > steps.get_versions.outputs.current_tag
      run: |
        make build
      working-directory: ${{ WORKING_DIR }}

    - name: Configure AWS credentials
      if: steps.get_versions.outputs.release_tag > steps.get_versions.outputs.current_tag
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      if: steps.get_versions.outputs.release_tag > steps.get_versions.outputs.current_tag
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Upload image
      if: steps.get_versions.outputs.release_tag > steps.get_versions.outputs.current_tag
      run: make push
      working-directory: ${{ WORKING_DIR }}

    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Update ${{ VERSION_STR }} to ${{ steps.get_versions.outputs.release_tag }}
        title: Update ${{ VERSION_STR }} to ${{ steps.get_versions.outputs.release_tag }}
        body: |
          Update ${{ VERSION_STR }} to ${{ steps.get_versions.outputs.release_tag }}

          Auto-generated by Github Actions
        labels: pe, cosmos-shard
        branch: cosmos-network-auto-updates
