name: tst

on:
  workflow_dispatch:

env:
  REPO_URL: https://api.github.com/repos/Kava-Labs/kava/releases/latest
  VERSION_ARG: KAVA_VERSION
  SUFFIX_ARG: KAVA_SUFFIX

jobs:
  build_and_upload:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Get versions
      id: get_versions
      run: |
          echo ::set-output name=release_tag::$(curl -sL $REPO_URL | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(export $(grep -e KAVA_VERSION -e KAVA_SUFFIX .env | xargs) && echo "v${KAVA_VERSION}${KAVA_SUFFIX}")
      working-directory: containers/kava

    - name: Build
      if: steps.get_versions.outputs.release_tag > steps.get_versions.outputs.current_tag
      env:
        RELEASE_TAG: ${{ steps.get_versions.outputs.release_tag }}
      run: |
        make build
      working-directory: containers/kava

    - name: Configure AWS credentials
      if: steps.get_versions.outputs.release_tag > steps.get_versions.outputs.current_tag
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      if: steps.get_versions.outputs.release_tag > steps.get_versions.outputs.current_tag
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Upload image
      if: steps.get_versions.outputs.release_tag > steps.get_versions.outputs.current_tag
      run: make push
      working-directory: containers/kava
